// <auto-generated />
using System;
using AlbrigeTransport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbrigeTransport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902211356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AlbrigeTransport.Models.AdminPasscode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasscodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminPasscodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasscodeHash = "13474678eaca9647778ea34ad98c59b6ef045cc1713e262902e3e35de455e4a9"
                        });
                });

            modelBuilder.Entity("AlbrigeTransport.Models.AdminSecurity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminSecurities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "13474678eaca9647778ea34ad98c59b6ef045cc1713e262902e3e35de455e4a9"
                        });
                });

            modelBuilder.Entity("AlbrigeTransport.Models.LectureSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatheringTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LectureTime")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "LectureTime")
                        .IsUnique();

                    b.ToTable("LectureSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GatheringTime = "06:50 AM",
                            LectureTime = "8:30",
                            StationId = 1
                        },
                        new
                        {
                            Id = 2,
                            GatheringTime = "08:00 AM",
                            LectureTime = "10:00",
                            StationId = 1
                        },
                        new
                        {
                            Id = 3,
                            GatheringTime = "09:45 AM",
                            LectureTime = "11:30",
                            StationId = 1
                        },
                        new
                        {
                            Id = 4,
                            GatheringTime = "06:55 AM",
                            LectureTime = "8:30",
                            StationId = 2
                        },
                        new
                        {
                            Id = 5,
                            GatheringTime = "08:05 AM",
                            LectureTime = "10:00",
                            StationId = 2
                        },
                        new
                        {
                            Id = 6,
                            GatheringTime = "09:50 AM",
                            LectureTime = "11:30",
                            StationId = 2
                        },
                        new
                        {
                            Id = 7,
                            GatheringTime = "07:05 AM",
                            LectureTime = "8:30",
                            StationId = 3
                        },
                        new
                        {
                            Id = 8,
                            GatheringTime = "08:15 AM",
                            LectureTime = "10:00",
                            StationId = 3
                        },
                        new
                        {
                            Id = 9,
                            GatheringTime = "10:00 AM",
                            LectureTime = "11:30",
                            StationId = 3
                        },
                        new
                        {
                            Id = 10,
                            GatheringTime = "07:10 AM",
                            LectureTime = "8:30",
                            StationId = 4
                        },
                        new
                        {
                            Id = 11,
                            GatheringTime = "08:25 AM",
                            LectureTime = "10:00",
                            StationId = 4
                        },
                        new
                        {
                            Id = 12,
                            GatheringTime = "10:05 AM",
                            LectureTime = "11:30",
                            StationId = 4
                        },
                        new
                        {
                            Id = 13,
                            GatheringTime = "07:25 AM",
                            LectureTime = "8:30",
                            StationId = 5
                        },
                        new
                        {
                            Id = 14,
                            GatheringTime = "08:45 AM",
                            LectureTime = "10:00",
                            StationId = 5
                        },
                        new
                        {
                            Id = 15,
                            GatheringTime = "10:15 AM",
                            LectureTime = "11:30",
                            StationId = 5
                        },
                        new
                        {
                            Id = 16,
                            GatheringTime = "07:25 AM",
                            LectureTime = "8:30",
                            StationId = 6
                        },
                        new
                        {
                            Id = 17,
                            GatheringTime = "08:45 AM",
                            LectureTime = "10:00",
                            StationId = 6
                        },
                        new
                        {
                            Id = 18,
                            GatheringTime = "10:15 AM",
                            LectureTime = "11:30",
                            StationId = 6
                        },
                        new
                        {
                            Id = 19,
                            GatheringTime = "07:30 AM",
                            LectureTime = "8:30",
                            StationId = 7
                        },
                        new
                        {
                            Id = 20,
                            GatheringTime = "08:55 AM",
                            LectureTime = "10:00",
                            StationId = 7
                        },
                        new
                        {
                            Id = 21,
                            GatheringTime = "10:20 AM",
                            LectureTime = "11:30",
                            StationId = 7
                        },
                        new
                        {
                            Id = 22,
                            GatheringTime = "07:32 AM",
                            LectureTime = "8:30",
                            StationId = 8
                        },
                        new
                        {
                            Id = 23,
                            GatheringTime = "08:57 AM",
                            LectureTime = "10:00",
                            StationId = 8
                        },
                        new
                        {
                            Id = 24,
                            GatheringTime = "10:22 AM",
                            LectureTime = "11:30",
                            StationId = 8
                        },
                        new
                        {
                            Id = 25,
                            GatheringTime = "07:35 AM",
                            LectureTime = "8:30",
                            StationId = 9
                        },
                        new
                        {
                            Id = 26,
                            GatheringTime = "09:00 AM",
                            LectureTime = "10:00",
                            StationId = 9
                        },
                        new
                        {
                            Id = 27,
                            GatheringTime = "10:25 AM",
                            LectureTime = "11:30",
                            StationId = 9
                        },
                        new
                        {
                            Id = 28,
                            GatheringTime = "07:40 AM",
                            LectureTime = "8:30",
                            StationId = 10
                        },
                        new
                        {
                            Id = 29,
                            GatheringTime = "09:10 AM",
                            LectureTime = "10:00",
                            StationId = 10
                        },
                        new
                        {
                            Id = 30,
                            GatheringTime = "10:30 AM",
                            LectureTime = "11:30",
                            StationId = 10
                        },
                        new
                        {
                            Id = 31,
                            GatheringTime = "07:00 AM",
                            LectureTime = "8:30",
                            StationId = 11
                        },
                        new
                        {
                            Id = 32,
                            GatheringTime = "08:20 AM",
                            LectureTime = "10:00",
                            StationId = 11
                        },
                        new
                        {
                            Id = 33,
                            GatheringTime = "09:45 AM",
                            LectureTime = "11:30",
                            StationId = 11
                        },
                        new
                        {
                            Id = 34,
                            GatheringTime = "07:05 AM",
                            LectureTime = "8:30",
                            StationId = 12
                        },
                        new
                        {
                            Id = 35,
                            GatheringTime = "08:25 AM",
                            LectureTime = "10:00",
                            StationId = 12
                        },
                        new
                        {
                            Id = 36,
                            GatheringTime = "09:55 AM",
                            LectureTime = "11:30",
                            StationId = 12
                        },
                        new
                        {
                            Id = 37,
                            GatheringTime = "07:10 AM",
                            LectureTime = "8:30",
                            StationId = 13
                        },
                        new
                        {
                            Id = 38,
                            GatheringTime = "08:30 AM",
                            LectureTime = "10:00",
                            StationId = 13
                        },
                        new
                        {
                            Id = 39,
                            GatheringTime = "10:00 AM",
                            LectureTime = "11:30",
                            StationId = 13
                        },
                        new
                        {
                            Id = 40,
                            GatheringTime = "07:13 AM",
                            LectureTime = "8:30",
                            StationId = 14
                        },
                        new
                        {
                            Id = 41,
                            GatheringTime = "08:35 AM",
                            LectureTime = "10:00",
                            StationId = 14
                        },
                        new
                        {
                            Id = 42,
                            GatheringTime = "10:03 AM",
                            LectureTime = "11:30",
                            StationId = 14
                        },
                        new
                        {
                            Id = 43,
                            GatheringTime = "07:20 AM",
                            LectureTime = "8:30",
                            StationId = 15
                        },
                        new
                        {
                            Id = 44,
                            GatheringTime = "08:50 AM",
                            LectureTime = "10:00",
                            StationId = 15
                        },
                        new
                        {
                            Id = 45,
                            GatheringTime = "10:10 AM",
                            LectureTime = "11:30",
                            StationId = 15
                        },
                        new
                        {
                            Id = 46,
                            GatheringTime = "07:25 AM",
                            LectureTime = "8:30",
                            StationId = 16
                        },
                        new
                        {
                            Id = 47,
                            GatheringTime = "08:55 AM",
                            LectureTime = "10:00",
                            StationId = 16
                        },
                        new
                        {
                            Id = 48,
                            GatheringTime = "10:15 AM",
                            LectureTime = "11:30",
                            StationId = 16
                        },
                        new
                        {
                            Id = 49,
                            GatheringTime = "07:35 AM",
                            LectureTime = "8:30",
                            StationId = 17
                        },
                        new
                        {
                            Id = 50,
                            GatheringTime = "09:05 AM",
                            LectureTime = "10:00",
                            StationId = 17
                        },
                        new
                        {
                            Id = 51,
                            GatheringTime = "10:25 AM",
                            LectureTime = "11:30",
                            StationId = 17
                        },
                        new
                        {
                            Id = 52,
                            GatheringTime = "07:38 AM",
                            LectureTime = "8:30",
                            StationId = 18
                        },
                        new
                        {
                            Id = 53,
                            GatheringTime = "09:08 AM",
                            LectureTime = "10:00",
                            StationId = 18
                        },
                        new
                        {
                            Id = 54,
                            GatheringTime = "10:28 AM",
                            LectureTime = "11:30",
                            StationId = 18
                        },
                        new
                        {
                            Id = 55,
                            GatheringTime = "07:40 AM",
                            LectureTime = "8:30",
                            StationId = 19
                        },
                        new
                        {
                            Id = 56,
                            GatheringTime = "09:10 AM",
                            LectureTime = "10:00",
                            StationId = 19
                        },
                        new
                        {
                            Id = 57,
                            GatheringTime = "10:30 AM",
                            LectureTime = "11:30",
                            StationId = 19
                        },
                        new
                        {
                            Id = 58,
                            GatheringTime = "06:55 AM",
                            LectureTime = "8:30",
                            StationId = 20
                        },
                        new
                        {
                            Id = 59,
                            GatheringTime = "08:15 AM",
                            LectureTime = "10:00",
                            StationId = 20
                        },
                        new
                        {
                            Id = 60,
                            GatheringTime = "09:45 AM",
                            LectureTime = "11:30",
                            StationId = 20
                        },
                        new
                        {
                            Id = 61,
                            GatheringTime = "07:00 AM",
                            LectureTime = "8:30",
                            StationId = 21
                        },
                        new
                        {
                            Id = 62,
                            GatheringTime = "08:20 AM",
                            LectureTime = "10:00",
                            StationId = 21
                        },
                        new
                        {
                            Id = 63,
                            GatheringTime = "09:50 AM",
                            LectureTime = "11:30",
                            StationId = 21
                        },
                        new
                        {
                            Id = 64,
                            GatheringTime = "07:10 AM",
                            LectureTime = "8:30",
                            StationId = 22
                        },
                        new
                        {
                            Id = 65,
                            GatheringTime = "08:35 AM",
                            LectureTime = "10:00",
                            StationId = 22
                        },
                        new
                        {
                            Id = 66,
                            GatheringTime = "10:05 AM",
                            LectureTime = "11:30",
                            StationId = 22
                        },
                        new
                        {
                            Id = 67,
                            GatheringTime = "07:15 AM",
                            LectureTime = "8:30",
                            StationId = 23
                        },
                        new
                        {
                            Id = 68,
                            GatheringTime = "08:45 AM",
                            LectureTime = "10:00",
                            StationId = 23
                        },
                        new
                        {
                            Id = 69,
                            GatheringTime = "10:15 AM",
                            LectureTime = "11:30",
                            StationId = 23
                        },
                        new
                        {
                            Id = 70,
                            GatheringTime = "07:20 AM",
                            LectureTime = "8:30",
                            StationId = 24
                        },
                        new
                        {
                            Id = 71,
                            GatheringTime = "08:50 AM",
                            LectureTime = "10:00",
                            StationId = 24
                        },
                        new
                        {
                            Id = 72,
                            GatheringTime = "10:20 AM",
                            LectureTime = "11:30",
                            StationId = 24
                        },
                        new
                        {
                            Id = 73,
                            GatheringTime = "07:25 AM",
                            LectureTime = "8:30",
                            StationId = 25
                        },
                        new
                        {
                            Id = 74,
                            GatheringTime = "08:55 AM",
                            LectureTime = "10:00",
                            StationId = 25
                        },
                        new
                        {
                            Id = 75,
                            GatheringTime = "10:20 AM",
                            LectureTime = "11:30",
                            StationId = 25
                        },
                        new
                        {
                            Id = 76,
                            GatheringTime = "07:30 AM",
                            LectureTime = "8:30",
                            StationId = 26
                        },
                        new
                        {
                            Id = 77,
                            GatheringTime = "09:00 AM",
                            LectureTime = "10:00",
                            StationId = 26
                        },
                        new
                        {
                            Id = 78,
                            GatheringTime = "10:25 AM",
                            LectureTime = "11:30",
                            StationId = 26
                        },
                        new
                        {
                            Id = 79,
                            GatheringTime = "07:35 AM",
                            LectureTime = "8:30",
                            StationId = 27
                        },
                        new
                        {
                            Id = 80,
                            GatheringTime = "09:05 AM",
                            LectureTime = "10:00",
                            StationId = 27
                        },
                        new
                        {
                            Id = 81,
                            GatheringTime = "10:30 AM",
                            LectureTime = "11:30",
                            StationId = 27
                        },
                        new
                        {
                            Id = 82,
                            GatheringTime = "07:45 AM",
                            LectureTime = "8:30",
                            StationId = 28
                        },
                        new
                        {
                            Id = 83,
                            GatheringTime = "09:15 AM",
                            LectureTime = "10:00",
                            StationId = 28
                        },
                        new
                        {
                            Id = 84,
                            GatheringTime = "10:40 AM",
                            LectureTime = "11:30",
                            StationId = 28
                        },
                        new
                        {
                            Id = 85,
                            GatheringTime = "07:50 AM",
                            LectureTime = "8:30",
                            StationId = 29
                        },
                        new
                        {
                            Id = 86,
                            GatheringTime = "09:20 AM",
                            LectureTime = "10:00",
                            StationId = 29
                        },
                        new
                        {
                            Id = 87,
                            GatheringTime = "10:45 AM",
                            LectureTime = "11:30",
                            StationId = 29
                        },
                        new
                        {
                            Id = 88,
                            GatheringTime = "07:55 AM",
                            LectureTime = "8:30",
                            StationId = 30
                        },
                        new
                        {
                            Id = 89,
                            GatheringTime = "09:25 AM",
                            LectureTime = "10:00",
                            StationId = 30
                        },
                        new
                        {
                            Id = 90,
                            GatheringTime = "10:50 AM",
                            LectureTime = "11:30",
                            StationId = 30
                        },
                        new
                        {
                            Id = 91,
                            GatheringTime = "06:30 AM",
                            LectureTime = "8:30",
                            StationId = 31
                        },
                        new
                        {
                            Id = 92,
                            GatheringTime = "07:45 AM",
                            LectureTime = "10:00",
                            StationId = 31
                        },
                        new
                        {
                            Id = 93,
                            GatheringTime = "06:30 AM",
                            LectureTime = "8:30",
                            StationId = 32
                        },
                        new
                        {
                            Id = 94,
                            GatheringTime = "07:50 AM",
                            LectureTime = "10:00",
                            StationId = 32
                        },
                        new
                        {
                            Id = 95,
                            GatheringTime = "06:35 AM",
                            LectureTime = "8:30",
                            StationId = 33
                        },
                        new
                        {
                            Id = 96,
                            GatheringTime = "07:50 AM",
                            LectureTime = "10:00",
                            StationId = 33
                        },
                        new
                        {
                            Id = 97,
                            GatheringTime = "06:35 AM",
                            LectureTime = "8:30",
                            StationId = 34
                        },
                        new
                        {
                            Id = 98,
                            GatheringTime = "07:50 AM",
                            LectureTime = "10:00",
                            StationId = 34
                        },
                        new
                        {
                            Id = 99,
                            GatheringTime = "06:40 AM",
                            LectureTime = "8:30",
                            StationId = 35
                        },
                        new
                        {
                            Id = 100,
                            GatheringTime = "07:55 AM",
                            LectureTime = "10:00",
                            StationId = 35
                        },
                        new
                        {
                            Id = 101,
                            GatheringTime = "06:45 AM",
                            LectureTime = "8:30",
                            StationId = 36
                        },
                        new
                        {
                            Id = 102,
                            GatheringTime = "08:00 AM",
                            LectureTime = "10:00",
                            StationId = 36
                        },
                        new
                        {
                            Id = 103,
                            GatheringTime = "06:45 AM",
                            LectureTime = "8:30",
                            StationId = 37
                        },
                        new
                        {
                            Id = 104,
                            GatheringTime = "08:00 AM",
                            LectureTime = "10:00",
                            StationId = 37
                        },
                        new
                        {
                            Id = 105,
                            GatheringTime = "06:50 AM",
                            LectureTime = "8:30",
                            StationId = 38
                        },
                        new
                        {
                            Id = 106,
                            GatheringTime = "08:10 AM",
                            LectureTime = "10:00",
                            StationId = 38
                        },
                        new
                        {
                            Id = 107,
                            GatheringTime = "06:55 AM",
                            LectureTime = "8:30",
                            StationId = 39
                        },
                        new
                        {
                            Id = 108,
                            GatheringTime = "08:15 AM",
                            LectureTime = "10:00",
                            StationId = 39
                        },
                        new
                        {
                            Id = 109,
                            GatheringTime = "07:00 AM",
                            LectureTime = "8:30",
                            StationId = 40
                        },
                        new
                        {
                            Id = 110,
                            GatheringTime = "08:20 AM",
                            LectureTime = "10:00",
                            StationId = 40
                        },
                        new
                        {
                            Id = 111,
                            GatheringTime = "07:00 AM",
                            LectureTime = "8:30",
                            StationId = 41
                        },
                        new
                        {
                            Id = 112,
                            GatheringTime = "08:25 AM",
                            LectureTime = "10:00",
                            StationId = 41
                        },
                        new
                        {
                            Id = 113,
                            GatheringTime = "07:40 AM",
                            LectureTime = "8:30",
                            StationId = 42
                        },
                        new
                        {
                            Id = 114,
                            GatheringTime = "07:45 AM",
                            LectureTime = "8:30",
                            StationId = 43
                        },
                        new
                        {
                            Id = 115,
                            GatheringTime = "06:50 AM",
                            LectureTime = "8:30",
                            StationId = 44
                        },
                        new
                        {
                            Id = 116,
                            GatheringTime = "06:55 AM",
                            LectureTime = "8:30",
                            StationId = 45
                        },
                        new
                        {
                            Id = 117,
                            GatheringTime = "07:00 AM",
                            LectureTime = "8:30",
                            StationId = 46
                        },
                        new
                        {
                            Id = 118,
                            GatheringTime = "07:55 AM",
                            LectureTime = "8:30",
                            StationId = 47
                        },
                        new
                        {
                            Id = 119,
                            GatheringTime = "07:05 AM",
                            LectureTime = "8:30",
                            StationId = 48
                        },
                        new
                        {
                            Id = 120,
                            GatheringTime = "07:10 AM",
                            LectureTime = "8:30",
                            StationId = 49
                        },
                        new
                        {
                            Id = 121,
                            GatheringTime = "07:15 AM",
                            LectureTime = "8:30",
                            StationId = 50
                        },
                        new
                        {
                            Id = 122,
                            GatheringTime = "07:20 AM",
                            LectureTime = "8:30",
                            StationId = 51
                        },
                        new
                        {
                            Id = 123,
                            GatheringTime = "07:25 AM",
                            LectureTime = "8:30",
                            StationId = 52
                        },
                        new
                        {
                            Id = 124,
                            GatheringTime = "07:30 AM",
                            LectureTime = "8:30",
                            StationId = 53
                        });
                });

            modelBuilder.Entity("AlbrigeTransport.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowScheduleTimes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusBadgeText")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShowScheduleTimes = true,
                            StatusBadgeText = "سالك",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AlbrigeTransport.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultGatheringTime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionOrLandmark")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DistanceText")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleMapsUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("StationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrafficStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportLineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransportLineId", "StationNumber")
                        .IsUnique();

                    b.ToTable("Stations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:50 AM",
                            DescriptionOrLandmark = "بجانب مسجد أبو نصير الكبير",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/dj1oUNbuQnK7DPXY7?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.051836000000002,
                            Longitude = 35.881073999999998,
                            StationName = "مسجد أبو نصير الكبير",
                            StationNumber = 1,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:55 AM",
                            DescriptionOrLandmark = "عند دوار الأميرة بسمة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=32.050787,35.884928",
                            ImagePath = "",
                            Latitude = 32.050787,
                            Longitude = 35.884928000000002,
                            StationName = "دوار الأميرة بسمة",
                            StationNumber = 2,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 3,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:05 AM",
                            DescriptionOrLandmark = "مقابل محمص الشعب في صويلح",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=32.024634,35.853415",
                            ImagePath = "",
                            Latitude = 32.024633999999999,
                            Longitude = 35.853414999999998,
                            StationName = "صويلح (محمص الشعب)",
                            StationNumber = 3,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 4,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:10 AM",
                            DescriptionOrLandmark = "قرب شركة الكهرباء في صويلح",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.95863,35.903898",
                            ImagePath = "",
                            Latitude = 31.958629999999999,
                            Longitude = 35.903897999999998,
                            StationName = "صويلح (شركة الكهرباء)",
                            StationNumber = 4,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 5,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:25 AM",
                            DescriptionOrLandmark = "مقابل مجمع خلدا التجاري",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.993584,35.830104",
                            ImagePath = "",
                            Latitude = 31.993583999999998,
                            Longitude = 35.830103999999999,
                            StationName = "دوار خلدا",
                            StationNumber = 5,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 6,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:25 AM",
                            DescriptionOrLandmark = "أسفل جسر المشاة مباشرة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.989812,35.830166",
                            ImagePath = "",
                            Latitude = 31.989812000000001,
                            Longitude = 35.830165999999998,
                            StationName = "حدائق الحسين (جسر المشاة)",
                            StationNumber = 6,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 7,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:30 AM",
                            DescriptionOrLandmark = "أمام محلات الدوار الرئيسية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.971761,35.83968",
                            ImagePath = "",
                            Latitude = 31.971761000000001,
                            Longitude = 35.839680000000001,
                            StationName = "دوار الشعب",
                            StationNumber = 7,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 8,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:32 AM",
                            DescriptionOrLandmark = "على الرصيف المقابل لمبنى زين عند جسر المشاة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.966627,35.842381",
                            ImagePath = "",
                            Latitude = 31.966626999999999,
                            Longitude = 35.842381000000003,
                            StationName = "مقابل شركة زين (جسر المشاة)",
                            StationNumber = 8,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 9,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:35 AM",
                            DescriptionOrLandmark = "بجانب فرع البنك التجاري تحت الجسر",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.953392,35.849005",
                            ImagePath = "",
                            Latitude = 31.953392000000001,
                            Longitude = 35.849004999999998,
                            StationName = "البنك التجاري (جسر المشاة)",
                            StationNumber = 9,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 10,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:40 AM",
                            DescriptionOrLandmark = "بجانب محطة المناصير عند جسر المشاة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.919624,35.859053",
                            ImagePath = "",
                            Latitude = 31.919623999999999,
                            Longitude = 35.859053000000003,
                            StationName = "كازية المناصير (جسر المشاة)",
                            StationNumber = 10,
                            TrafficStatus = "سالك",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 11,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:00 AM",
                            DescriptionOrLandmark = "عند مبنى الاستشارات في الجامعة الأردنية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=32.022712,35.873373",
                            ImagePath = "",
                            Latitude = 32.022711999999999,
                            Longitude = 35.873373000000001,
                            StationName = "الاستشارات",
                            StationNumber = 1,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 12,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:05 AM",
                            DescriptionOrLandmark = "مقابل مستشفى الإسراء",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=32.01731,35.86593",
                            ImagePath = "",
                            Latitude = 32.017310000000002,
                            Longitude = 35.865929999999999,
                            StationName = "مستشفى الإسراء",
                            StationNumber = 2,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 13,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:10 AM",
                            DescriptionOrLandmark = "كازية توتال على شارع الجامعة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=32.005778,35.87265",
                            ImagePath = "",
                            Latitude = 32.005777999999999,
                            Longitude = 35.87265,
                            StationName = "كازية توتال (شارع الجامعة)",
                            StationNumber = 3,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 14,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:13 AM",
                            DescriptionOrLandmark = "تحت جسر المشاة مقابل مستشفى ابن الهيثم",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.998518,35.872352",
                            ImagePath = "",
                            Latitude = 31.998518000000001,
                            Longitude = 35.872351999999999,
                            StationName = "مقابل مستشفى ابن الهيثم (جسر المشاة)",
                            StationNumber = 4,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 15,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:20 AM",
                            DescriptionOrLandmark = "عند دوار الواحة قرب حلويات حبيبة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.98867,35.866872",
                            ImagePath = "",
                            Latitude = 31.988669999999999,
                            Longitude = 35.866872000000001,
                            StationName = "دوار الواحة (حبيبة)",
                            StationNumber = 5,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 16,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:25 AM",
                            DescriptionOrLandmark = "عند دوار الكيلو أسفل جسر المشاة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.971271,35.86463",
                            ImagePath = "",
                            Latitude = 31.971271000000002,
                            Longitude = 35.864629999999998,
                            StationName = "دوار الكيلو (جسر المشاة)",
                            StationNumber = 6,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 17,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:35 AM",
                            DescriptionOrLandmark = "عند دوار سيفوي في السابع",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.954169,35.857338",
                            ImagePath = "",
                            Latitude = 31.954169,
                            Longitude = 35.857337999999999,
                            StationName = "السابع (دوار السيفوي)",
                            StationNumber = 7,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 18,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:38 AM",
                            DescriptionOrLandmark = "بجانب كازية جولف في السابع",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.942379,35.857223",
                            ImagePath = "",
                            Latitude = 31.942378999999999,
                            Longitude = 35.857222999999998,
                            StationName = "كازية جولف (السابع)",
                            StationNumber = 8,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 19,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:40 AM",
                            DescriptionOrLandmark = "بجانب محطة المناصير عند جسر المشاة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.919624,35.859053",
                            ImagePath = "",
                            Latitude = 31.919623999999999,
                            Longitude = 35.859053000000003,
                            StationName = "كازية المناصير (جسر المشاة)",
                            StationNumber = 9,
                            TrafficStatus = "سالك",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 20,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:55 AM",
                            DescriptionOrLandmark = "أمام مدخل عريفة مول في طبربور",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.992506,35.934311",
                            ImagePath = "",
                            Latitude = 31.992505999999999,
                            Longitude = 35.934311000000001,
                            StationName = "عريفة مول",
                            StationNumber = 1,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 21,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:00 AM",
                            DescriptionOrLandmark = "محطة Go قبل مجمع الشمال",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.993998,35.921451",
                            ImagePath = "",
                            Latitude = 31.993998000000001,
                            Longitude = 35.921450999999998,
                            StationName = "كازية Go (مجمع الشمال)",
                            StationNumber = 2,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 22,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:10 AM",
                            DescriptionOrLandmark = "عند دوار المدينة الرياضية بعد السيرفيس",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.984842,35.89866",
                            ImagePath = "",
                            Latitude = 31.984842,
                            Longitude = 35.89866,
                            StationName = "دوار المدينة الرياضية (بعد السيرفيس)",
                            StationNumber = 3,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 23,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:15 AM",
                            DescriptionOrLandmark = "بجانب مجمع بنك الإسكان",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.970882,35.907258",
                            ImagePath = "",
                            Latitude = 31.970882,
                            Longitude = 35.907257999999999,
                            StationName = "الداخلية (مجمع بنك الإسكان)",
                            StationNumber = 4,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 24,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:20 AM",
                            DescriptionOrLandmark = "على رصيف الدوار الرابع",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.956087,35.895882",
                            ImagePath = "",
                            Latitude = 31.956087,
                            Longitude = 35.895882,
                            StationName = "الدوار الرابع",
                            StationNumber = 5,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 25,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:25 AM",
                            DescriptionOrLandmark = "قرب دوار عبدون",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.948436,35.892195",
                            ImagePath = "",
                            Latitude = 31.948436000000001,
                            Longitude = 35.892195000000001,
                            StationName = "دوار عبدون",
                            StationNumber = 6,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 26,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:30 AM",
                            DescriptionOrLandmark = "أمام مدخل تاج مول",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.941013,35.888717",
                            ImagePath = "",
                            Latitude = 31.941013000000002,
                            Longitude = 35.888717,
                            StationName = "تاج مول",
                            StationNumber = 7,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 27,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:35 AM",
                            DescriptionOrLandmark = "محطة جو بترول على كوردور عبدون",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.92716,35.876121",
                            ImagePath = "",
                            Latitude = 31.927160000000001,
                            Longitude = 35.876120999999998,
                            StationName = "كوريدور عبدون (كازية جوبيترول)",
                            StationNumber = 8,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 28,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:45 AM",
                            DescriptionOrLandmark = "عند دوار البرديني في مرج الحمام",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.902713,35.846609",
                            ImagePath = "",
                            Latitude = 31.902712999999999,
                            Longitude = 35.846609000000001,
                            StationName = "مرج الحمام (دوار البرديني)",
                            StationNumber = 9,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 29,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:50 AM",
                            DescriptionOrLandmark = "عند إشارات الكنيسة في مرج الحمام",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.898829,35.858485",
                            ImagePath = "",
                            Latitude = 31.898828999999999,
                            Longitude = 35.858485000000002,
                            StationName = "مرج الحمام (إشارات الكنيسة)",
                            StationNumber = 10,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 30,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:55 AM",
                            DescriptionOrLandmark = "محمص الشعب على طريق السلام",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.872623,35.83713",
                            ImagePath = "",
                            Latitude = 31.872623000000001,
                            Longitude = 35.837130000000002,
                            StationName = "محمص الشعب (طريق السلام)",
                            StationNumber = 11,
                            TrafficStatus = "سالك",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 31,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:30 AM",
                            DescriptionOrLandmark = "مثلث جامعة البلقاء التطبيقية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/7YNEies2FAHa2LpK8?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.021844999999999,
                            Longitude = 35.713487000000001,
                            StationName = "مثلث جامعة البلقاء",
                            StationNumber = 1,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 32,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:30 AM",
                            DescriptionOrLandmark = "عند جسر وادي حادي",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/2ACujcmjCPZE4Zgn8?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.031329999999997,
                            Longitude = 35.713769999999997,
                            StationName = "جسر وادي حادي",
                            StationNumber = 2,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 33,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:35 AM",
                            DescriptionOrLandmark = "قرب جسر المغاريب",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/jMs2kNvwyAzbUuiE7?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.035232999999998,
                            Longitude = 35.702998000000001,
                            StationName = "جسر المغاريب",
                            StationNumber = 3,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 34,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:35 AM",
                            DescriptionOrLandmark = "عند جسر الدباس",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/HEjV7NFpSvUsDRjY6?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.051000000000002,
                            Longitude = 35.701300000000003,
                            StationName = "جسر الدباس",
                            StationNumber = 4,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 35,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:40 AM",
                            DescriptionOrLandmark = "عند مثلث المدينة الرياضية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/iHNsYTDDnpuc6jL47?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.060516,
                            Longitude = 35.701256000000001,
                            StationName = "مثلث المدينة الرياضية",
                            StationNumber = 5,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 36,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:45 AM",
                            DescriptionOrLandmark = "أمام مجمع المناصير",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/KJ9by3ZuxU3PcSCr7?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.065561000000002,
                            Longitude = 35.724066999999998,
                            StationName = "مجمع المناصير",
                            StationNumber = 6,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 37,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:45 AM",
                            DescriptionOrLandmark = "عند إشارة الدفاع المدني",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/E6AS1PCsQZPzVtfaA?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.063352999999999,
                            Longitude = 35.737842999999998,
                            StationName = "إشارة الدفاع المدني",
                            StationNumber = 7,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 38,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:50 AM",
                            DescriptionOrLandmark = "عند جسر الدبابنة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/vRPmrruaTCuc5cxn8?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.057433000000003,
                            Longitude = 35.747394,
                            StationName = "جسر الدبابنة",
                            StationNumber = 8,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 39,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:55 AM",
                            DescriptionOrLandmark = "على إشارة عين الباشا",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/VNANJgRjRRocnGL37?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.040517000000001,
                            Longitude = 35.786078000000003,
                            StationName = "إشارة عين الباشا",
                            StationNumber = 9,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 40,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:00 AM",
                            DescriptionOrLandmark = "عند دوار أم النعاج",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/foga5s7ALZij5eqh6?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.027538,
                            Longitude = 35.798774999999999,
                            StationName = "دوار أم النعاج",
                            StationNumber = 10,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 41,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:00 AM",
                            DescriptionOrLandmark = "عند دوار الكمالية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/SoVksVXvTcgozzkQA?g_st=aw",
                            ImagePath = "",
                            Latitude = 32.028785999999997,
                            Longitude = 35.825091,
                            StationName = "دوار الكمالية",
                            StationNumber = 11,
                            TrafficStatus = "سالك",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 42,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:40 AM",
                            DescriptionOrLandmark = "الرجيب — جنوب سحاب",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/mBMLHg6oMoFqjMvk8",
                            ImagePath = "",
                            Latitude = 31.882114999999999,
                            Longitude = 35.992024000000001,
                            StationName = "الرجيب (بداية الخط)",
                            StationNumber = 1,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 43,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:45 AM",
                            DescriptionOrLandmark = "الرجيب — سحاب",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/ZNgp5S4AZGYYbXx18",
                            ImagePath = "",
                            Latitude = 31.892364000000001,
                            Longitude = 35.979774999999997,
                            StationName = "إشارة مدخل سحاب",
                            StationNumber = 2,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 44,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:50 AM",
                            DescriptionOrLandmark = "أبو علندا — القويسمة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/Pw5m7LqbHfhDP8bZ9",
                            ImagePath = "",
                            Latitude = 31.899619000000001,
                            Longitude = 35.960177000000002,
                            StationName = "صيدلية تلال سلوان (قبل جسر مرسيدس)",
                            StationNumber = 3,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 45,
                            AdminNotes = "",
                            DefaultGatheringTime = "06:55 AM",
                            DescriptionOrLandmark = "أبو علندا — القويسمة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/bCCi7pw4n4tVbN839",
                            ImagePath = "",
                            Latitude = 31.901107,
                            Longitude = 35.937694999999998,
                            StationName = "البنك الإسلامي (جسر أبو علندا)",
                            StationNumber = 4,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 46,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:00 AM",
                            DescriptionOrLandmark = "المقابلين — شارع الحرية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/A1tc2aLaPp5E1Wez8",
                            ImagePath = "",
                            Latitude = 31.900479000000001,
                            Longitude = 35.931444999999997,
                            StationName = "دوار الجمرك",
                            StationNumber = 5,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 47,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:55 AM",
                            DescriptionOrLandmark = "المقابلين — أم قصير",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/67DCNjF37Hp1YBii8",
                            ImagePath = "",
                            Latitude = 31.895980000000002,
                            Longitude = 35.912909999999997,
                            StationName = "دوار الحويان",
                            StationNumber = 6,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 48,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:05 AM",
                            DescriptionOrLandmark = "المقابلين — شارع الحرية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/3d8v7UYaCND4dB1n7",
                            ImagePath = "",
                            Latitude = 31.896501000000001,
                            Longitude = 35.903098,
                            StationName = "إشارة أبو زغلة",
                            StationNumber = 7,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 49,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:10 AM",
                            DescriptionOrLandmark = "المقابلين — شارع الحرية",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/XTmm9u83w197ropH6",
                            ImagePath = "",
                            Latitude = 31.902439000000001,
                            Longitude = 35.890802000000001,
                            StationName = "إشارة الحفاظ",
                            StationNumber = 8,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 50,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:15 AM",
                            DescriptionOrLandmark = "القويسمة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/Tg1BUt8cTXpiAsCz5",
                            ImagePath = "",
                            Latitude = 31.911683,
                            Longitude = 35.881439999999998,
                            StationName = "تقاطع الإرسال",
                            StationNumber = 9,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 51,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:20 AM",
                            DescriptionOrLandmark = "الياسمين — القويسمة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/2a7K35KiW4CM8caBA",
                            ImagePath = "",
                            Latitude = 31.914325999999999,
                            Longitude = 35.887165000000003,
                            StationName = "إشارة حي الصحابة",
                            StationNumber = 10,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 52,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:25 AM",
                            DescriptionOrLandmark = "القويسمة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://maps.app.goo.gl/jk6y5KDxbtRLY59x5",
                            ImagePath = "",
                            Latitude = 31.920332999999999,
                            Longitude = 35.894745999999998,
                            StationName = "دوار قرقش",
                            StationNumber = 11,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        },
                        new
                        {
                            Id = 53,
                            AdminNotes = "",
                            DefaultGatheringTime = "07:30 AM",
                            DescriptionOrLandmark = "منطقة الياسمين — القويسمة",
                            DistanceText = "",
                            GoogleMapsUrl = "https://www.google.com/maps?q=31.9168,35.8892",
                            ImagePath = "",
                            Latitude = 31.916799999999999,
                            Longitude = 35.889200000000002,
                            StationName = "دوار الياسمين",
                            StationNumber = 12,
                            TrafficStatus = "سالك",
                            TransportLineId = 5
                        });
                });

            modelBuilder.Entity("AlbrigeTransport.Models.TransportLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionOrRouteRange")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GatheringPointsCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisibleInPublicMenu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LineNumber")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TransportLines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionOrRouteRange = "من مسجد أبو نصير الكبير وحتى كازية المناصير",
                            EstimatedDurationMinutes = 55,
                            GatheringPointsCount = 10,
                            IsVisibleInPublicMenu = true,
                            LineName = "خط أبو نصير",
                            LineNumber = 1,
                            Slug = "line-1",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            DescriptionOrRouteRange = "من الاستشارات وحتى كازية المناصير",
                            EstimatedDurationMinutes = 55,
                            GatheringPointsCount = 9,
                            IsVisibleInPublicMenu = true,
                            LineName = "خط الاستشارات",
                            LineNumber = 2,
                            Slug = "line-2",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            DescriptionOrRouteRange = "من عريفة مول وحتى محمص الشعب على طريق السلام",
                            EstimatedDurationMinutes = 65,
                            GatheringPointsCount = 11,
                            IsVisibleInPublicMenu = true,
                            LineName = "خط عريفة مول",
                            LineNumber = 3,
                            Slug = "line-3",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            DescriptionOrRouteRange = "من مثلث جامعة البلقاء وحتى دوار الكمالية",
                            EstimatedDurationMinutes = 66,
                            GatheringPointsCount = 11,
                            IsVisibleInPublicMenu = true,
                            LineName = "خط السلط",
                            LineNumber = 4,
                            Slug = "line-4",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            DescriptionOrRouteRange = "خط جنوب عمّان — من مدخل سحاب حتى دوار الياسمين",
                            EstimatedDurationMinutes = 50,
                            GatheringPointsCount = 12,
                            IsVisibleInPublicMenu = true,
                            LineName = "خط سحاب",
                            LineNumber = 5,
                            Slug = "line-5",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AlbrigeTransport.Models.UniversityDepartureTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeString")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportLineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransportLineId");

                    b.ToTable("UniversityDepartureTimes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TimeString = "11:40 AM",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 2,
                            TimeString = "01:10 PM",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 3,
                            TimeString = "02:40 PM",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 4,
                            TimeString = "04:40 PM",
                            TransportLineId = 1
                        },
                        new
                        {
                            Id = 5,
                            TimeString = "11:40 AM",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 6,
                            TimeString = "01:10 PM",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 7,
                            TimeString = "02:40 PM",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 8,
                            TimeString = "04:40 PM",
                            TransportLineId = 2
                        },
                        new
                        {
                            Id = 9,
                            TimeString = "11:40 AM",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 10,
                            TimeString = "01:10 PM",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 11,
                            TimeString = "02:40 PM",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 12,
                            TimeString = "04:40 PM",
                            TransportLineId = 3
                        },
                        new
                        {
                            Id = 13,
                            TimeString = "02:40 PM",
                            TransportLineId = 4
                        },
                        new
                        {
                            Id = 14,
                            TimeString = "04:40 PM",
                            TransportLineId = 5
                        });
                });

            modelBuilder.Entity("AlbrigeTransport.Models.LectureSchedule", b =>
                {
                    b.HasOne("AlbrigeTransport.Models.Station", "Station")
                        .WithMany("LectureSchedules")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AlbrigeTransport.Models.Station", b =>
                {
                    b.HasOne("AlbrigeTransport.Models.TransportLine", "Line")
                        .WithMany("Stations")
                        .HasForeignKey("TransportLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("AlbrigeTransport.Models.UniversityDepartureTime", b =>
                {
                    b.HasOne("AlbrigeTransport.Models.TransportLine", "Line")
                        .WithMany("UniversityDepartureTimes")
                        .HasForeignKey("TransportLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("AlbrigeTransport.Models.Station", b =>
                {
                    b.Navigation("LectureSchedules");
                });

            modelBuilder.Entity("AlbrigeTransport.Models.TransportLine", b =>
                {
                    b.Navigation("Stations");

                    b.Navigation("UniversityDepartureTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
